package GUI;


import com.mycompany.mavenproject6.Main;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pojo.Polozka;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("REMOVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        updateTable();
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("SORT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton1)
                        .addGap(53, 53, 53)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ADD add = new ADD();add.setVisible(true);add.setSize(400, 400);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        DELETE d=new DELETE();d.setVisible(true);d.setSize(400,300);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        List<Polozka> o=Main.listItems();

        Collections.sort(o, new CountSorter ());updateTable2((ArrayList<Polozka>) o);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
       /// SessionFactory sessionFactory = HibernateUtil.getInstnce();
		//	Session session = sessionFactory.openSession();		
		//Main m=new Main();	
			
	updateTable();	
        
    }

      static void updateTable(){
jTable1 = new javax.swing.JTable();
DefaultTableModel model =  new DefaultTableModel();
   model.fireTableDataChanged();

 
jTable1.setModel(model);
List<Polozka> zoz=new ArrayList();

   zoz= Main.listItems();


Object [] columnData=new Object[zoz.size()];
Object [] columnData2=new Object[zoz.size()];
Object [] columnData3=new Object[zoz.size()];
Object [] columnData4=new Object[zoz.size()];
Object [] columnData5=new Object[zoz.size()];



for (int i=0;i<zoz.size();i++){
columnData[i] = zoz.get(i).getId();
columnData2[i] = zoz.get(i).getTovar();
columnData3[i] = zoz.get(i).getMenopreb();
columnData4[i] = zoz.get(i).getPocetkusov();
columnData5[i] = zoz.get(i).getKrajina();
}

model.addColumn("Id", columnData);


     model.addColumn("Tovar",columnData2 );
        model.addColumn("Name",columnData3);
        model.addColumn("Kusy",columnData4);
 model.addColumn("Krajina",columnData5);
jScrollPane1.setViewportView(jTable1); 
zoz.clear();
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private static javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

  public class CountSorter implements Comparator<Polozka>{

    @Override
    public int compare(Polozka one, Polozka another){
        int returnVal = 0;

    if(one.getPocetkusov()< another.getPocetkusov()){
        returnVal =  -1;
    }else if(one.getPocetkusov() > another.getPocetkusov()){
        returnVal =  1;
    }else if(one.getPocetkusov() == another.getPocetkusov()){
        returnVal =  0;
    }
    return returnVal;
    }
}
  
   private void updateTable2(ArrayList<Polozka>p){
jTable1 = new javax.swing.JTable();
DefaultTableModel model =  new DefaultTableModel();
   model.fireTableDataChanged();

 
jTable1.setModel(model);
ArrayList<Polozka> zoz=new ArrayList();
zoz.clear();
   zoz= p;


Object [] columnData=new Object[zoz.size()];
Object [] columnData2=new Object[zoz.size()];
Object [] columnData3=new Object[zoz.size()];
Object [] columnData4=new Object[zoz.size()];
Object [] columnData5=new Object[zoz.size()];



for (int i=0;i<zoz.size();i++){
columnData[i] = zoz.get(i).getId();
columnData2[i] = zoz.get(i).getTovar();
columnData3[i] = zoz.get(i).getMenopreb();
columnData4[i] = zoz.get(i).getPocetkusov();
columnData5[i] = zoz.get(i).getKrajina();
}

model.addColumn("Id", columnData);


     model.addColumn("Tovar",columnData2 );
        model.addColumn("Name",columnData3);
        model.addColumn("Kusy",columnData4);
 model.addColumn("Krajina",columnData5);
jScrollPane1.setViewportView(jTable1); 

zoz.clear();

}
}
